Repository kanak227/NGO-WEBSITE, pull requests merged in 2025-04, with the labels that each got.

#125 Home Page made Responsive
  index.html
  styles/styles.css
Labels: enhancement, good first issue, hard, apertre2.0

#126 Made error 404 responsive
  404.html
Labels: enhancement, medium, apertre2.0

#102 Issue#97 added favicon to every page
  404.html
  assets/favicon.png
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/index2.html
  pages/login.html
  pages/news.html
  pages/register.html
Labels: medium, apertre2.0

#140 Fix logo issue on contact page
  pages/contact.html
  pages/news.html
Labels: bug, enhancement, good first issue, easy, apertre2.0

#149 Solved #143
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
  styles/styles.css
Labels: easy, apertre2.0

#156 improved css
  styles/styles.css
Labels: enhancement, easy, apertre2.0

#158 generalized animation timings and colour generalized
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/events.css
  styles/login.css
  styles/news.css
  styles/register.css
  styles/styles.css
Labels: good first issue, medium, apertre2.0

#165 Changes made
  index.html
  styles/news.css
  styles/styles.css
Labels: easy, apertre2.0

#187 Implement Dark Theme
  app.js
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/login.html
  pages/news.html
  pages/register.html
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/events.css
  styles/login.css
  styles/news.css
  styles/register.css
  styles/styles.css
Labels: hard, apertre2.0

#191 Created the Event Register Page
  index.html
  pages/eventRegister.html
  pages/events.html
  styles/eventRegister.css
  styles/styles.css
  validation.js
Labels: medium, apertre2.0

#194 Donation
  pages/donation.HTML
  pages/register.html
  styles/donation.css
  styles/login.css
  styles/register.css
Labels: good first issue, medium, apertre2.0

#196 Gradient Compatibility
  pages/register.html
  styles/404.css
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/eventRegister.css
  styles/events.css
  styles/index2.css
  styles/login.css
  styles/news.css
  styles/register.css
  styles/styles.css
Labels: medium, apertre2.0

#204 enhance events cards
  index.html
  styles/styles.css
Labels: good first issue, medium, apertre2.0

#205 Added a custom scroll bar
  styles/styles.css
Labels: easy, apertre2.0

#211 Added newsletter in home page and donation page
  index.html
  pages/donation.HTML
  styles/styles.css
Labels: enhancement, easy, apertre2.0

#224 added about us page
  assets/1742199533.jpg
  assets/2147621495.jpg
  assets/2148803915.jpg
  index.html
  pages/about.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
  styles/about.css
Labels: good first issue, hard, apertre2.0

#226 feature: dark-mode for events cards
  styles/styles.css
Labels: medium, apertre2.0

#228 Added dark mode
  pages/eventRegister.html
  styles/eventRegister.css
Labels: easy, apertre2.0

#232 Added return to home, enhanced text, added hover
  pages/about.html
  styles/about.css
Labels: easy, apertre2.0

#231 Improve the causes section
  pages/causes.html
  styles/causes.css
Labels: easy, apertre2.0
