Repository kanak227/NGO-WEBSITE, pull requests merged in 2025-03, with the labels that each got.

#19 Solved #issue2
  index.html
  styles.css
Labels: enhancement, easy, apertre2.0

#23 Issue #13 solved
  causes.html
  contact.html
  donation.HTML
  events.html
  index2.html
  news.html
Labels: enhancement, easy, apertre2.0

#22 Issue #3 Solved
  index.html
  login.html
  register.html
  styles.css
Labels: enhancement, good first issue, easy, apertre2.0

#25 Added real-time validation for contact form
  contact.html
Labels: good first issue, easy, apertre2.0

#26 ISSUE #24 SOLVED
  causes.html
  contact.html
  donation.HTML
  events.html
  news.html
Labels: easy, apertre2.0

#27 Updated with properly assigned links in footer
  causes.html
  contact.html
  events.html
  index.html
  news.html
Labels: bug, easy, apertre2.0

#28 Back to top button
  app.js
  index.html
  moon.png
  styles.css
  sun.png
Labels: enhancement, good first issue, medium, apertre2.0

#32 Enhnaced navbar
  styles.css
Labels: enhancement, good first issue, easy, apertre2.0

#35 animated 404 error page added
  404.html
Labels: good first issue, easy, apertre2.0

#39 Create MIT License.md
  MIT License.md
Labels: documentation, apertre2.0

#34 Solved Issue #33
  assets/1692610743456.jpeg
  assets/HD-wallpaper-with-love-lovely-romantic-romance-rose-book-beautiful-roses-red-rose-flowers-nature.jpg
  assets/NGO WEBSITE.png
  assets/background.png
  assets/card1.png
  assets/card2.png
  assets/card3.png
  assets/card4.png
  assets/card5.png
  assets/card6.png
  assets/children.png
  assets/childsmile.jpeg
  assets/donation.jpg
  assets/donor1.png
  assets/donor2.png
  assets/donor3.png
  assets/donor4.png
  assets/event.png
  assets/img1.png
  assets/img2.png
  assets/img3.jpg
  assets/img3.png
  assets/img4.png
  assets/img5.png
  assets/img6.png
  assets/kids.jpg
  assets/logo.png.png
  assets/main.png
  assets/message.png
  assets/moon.png
  assets/paypal.png
  assets/pic1.png
  assets/picture.png
  assets/poverty.png
  assets/querty.png
  assets/shake.png
  assets/skrill.png
  assets/sun.png
  assets/visa.png
  assets/water-icon.png
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/index2.html
  pages/login.html
  pages/news.html
  pages/register.html
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/events.css
  styles/index2.css
  styles/login.css
  styles/news.css
  styles/register.css
  styles/styles.css
Labels: bug, easy, apertre2.0

#47 Dynamic Numbers
  app.js
  index.html
  styles/styles.css
Labels: easy, apertre2.0

#49 Add responsiveness to website
  index.html
  styles/styles.css
Labels: medium, apertre2.0

#69 Issue no #65 [Bug]: Donate now button position fix along with 404 error fixing.
  index.html
  pages/donation.HTML
Labels: enhancement, easy, apertre2.0

#80 Navbar Bug
  app.js
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/index2.html
  pages/login.html
  pages/news.html
  pages/register.html
  styles/styles.css
Labels: hard, apertre2.0

#89 Code Refactored and comments added
  404.html
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/login.html
  pages/news.html
  pages/register.html
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/events.css
  styles/index2.css
  styles/login.css
  styles/news.css
  styles/register.css
  styles/styles.css
Labels: medium, apertre2.0

#92 Replaced All Lorem Ipsum with meaningfull content
  404.html
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
  pages/register.html
Labels: easy, apertre2.0

#95 Added Bact-to-Top button to all pages
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
Labels: easy, apertre2.0

#105 Responsiveness of all pages fixed except Home Page
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
  styles/causes.css
  styles/contact.css
  styles/donation.css
  styles/events.css
  styles/news.css
Labels: hard, apertre2.0

#104 Solved the contact info issue
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
Labels: easy, apertre2.0

#112 Improved button linking
  .vscode/settings.json
  app.js
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/login.html
  pages/news.html
  pages/register.html
Labels: good first issue, medium, apertre2.0

#96 improved the ui and some function in news page
  pages/news.html
  styles/news.css
Labels: enhancement, easy, apertre2.0

#115 Added the Footer to donation page
  pages/donation.HTML
Labels: good first issue, easy, apertre2.0

#117 Button
  styles/styles.css
Labels: medium, apertre2.0

#118 replaced the logo of twitter with its new one
  index.html
  pages/causes.html
  pages/contact.html
  pages/donation.HTML
  pages/events.html
  pages/news.html
Labels: good first issue, easy, apertre2.0

#119 Added proper ARIA attributes to SVG elements for screen reader compatability
  404.html
Labels: easy, apertre2.0
